INSERT INTO RESPOSTAS (ENQUETES_ID, RESPOSTA, VOTOS) VALUES (1, 'Segurança',  0);
INSERT INTO RESPOSTAS (ENQUETES_ID, RESPOSTA, VOTOS) VALUES (1, 'Banco de dados', 0);
INSERT INTO RESPOSTAS (ENQUETES_ID, RESPOSTA, VOTOS) VALUES (1, 'Manipulação de Imagens',  0);
INSERT INTO RESPOSTAS (ENQUETES_ID, RESPOSTA, VOTOS) VALUES (1, 'Orientação à Objetos',  0);
