CREATE TABLE PRODUTOS 
(
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PRODUTO VARCHAR(255) NULL,
  VALOR DOUBLE NULL,
  QUANTIDADE INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID)
);
 
INSERT INTO PRODUTOS (PRODUTO, VALOR, QUANTIDADE) VALUES('Telefone s/ fio', 65.5, 3);
INSERT INTO PRODUTOS (PRODUTO, VALOR, QUANTIDADE) VALUES('Celular', 129.5, 2);
INSERT INTO PRODUTOS (PRODUTO, VALOR, QUANTIDADE) VALUES('Notebook', 1399, 1);
