CREATE TABLE ENQUETES 
(
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ENQUETE VARCHAR(255) NULL,
  PRIMARY KEY(ID)
);
 
CREATE TABLE RESPOSTAS 
(
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ENQUETES_ID INTEGER UNSIGNED NOT NULL,
  RESPOSTA VARCHAR(255) NULL,
  VOTOS INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID, ENQUETES_ID),
  INDEX RESPOSTAS_FKIndex1(ENQUETES_ID)
);
